server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:33306/jeux
    username: user
    password: password
  jpa:
    show-sql: true
logging:
  level:
    sql: DEBUG